baseURL = "https://nav.uninett.no/"
languageCode = "en-us"
title = "Network Administration Visualized"
theme = "navsite"

[permalinks]
  blog = '/blog/:year/:month/:title/'

[markup.goldmark.parser]
  autoHeadingID = false
